### ISSUE TITLE
French translations not working for certain UI elements despite correct translation keys

### ISSUE THREAD

**Issue by geosigno** [muxinc/media-chrome#1147]
I'm implementing French translations for media-chrome and have discovered that several UI elements remain in English despite having the correct translation keys in my translation object. Specifically, the following elements don't translate to French:

"Play" button
"Quality" settings
"Enter picture in picture mode" button
Full Screen mode
Playback Speed
etc.

**Comment by Jerricho93** [comment]
Hey @geosigno thanks for reporting this!
 
I took a look at the docs for the media-chrome translations, and I believe that there are some minor enhancements needed on that front. I created a [small HTML project](https://codesandbox.io/p/sandbox/practical-bhabha-qysgg8) to test it, and I managed to get the elements that you mentioned translated in French (notice the imports, which are the tricky part. This will be updated in the docs soon to give more clarity about how to use the translations).

If you're still encountering this issue (maybe you're running this over some framework and not plain HTML) could you provide us with a code example so that we can help you more? Thanks in advance!

**Comment by geosigno** [comment]
Thanks for your reply. I actually managed to make it work, though I’m not exactly sure how. However, I still have an issue. I hardcoded lang="fr" on the media controller. When I use it in my test environment, it works fine, but once it’s imported into another project (I’m using it as a plugin via a npm repo), the language is in English, even though lang="fr" is hardcoded in the media controller.
I’m not sure if it’s related, but I’m using the React version.

**Comment by Jerricho93** [comment]
Hey @geosigno I used our example apps from this repo (we have some of them with React) and managed to get the labels properly translated. Would you mind giving us some working code (if possible) with how you're using your it in your project to see if there's anything that we can do from our end?

Thanks!

**Comment by Jerricho93** [comment]
Actually, @geosigno we were just able to reproduce your issue. It seems that this is a regression, I had an outdated branch. We are working on a fix right now, we will let you know when this is tackled

**Comment by geosigno** [comment]
Glad to hear, any update on that subject ?

Thanks !

**Comment by Jerricho93** [comment]
Hey @geosigno this issue has been solved in [this PR](https://github.com/muxinc/media-chrome/pull/1152) and will be live in the next media-chrome release. Thanks for reporting the issue and providing examples to help us fix it!

**Comment by geosigno** [comment]
This is still not working on my side. Even when hardcoding the lang to "fr" in the media controller, the tooltips are still in English. This only happens when the player is imported from another npm package. When testing locally, it works fine. Any idea?

**Comment by Jerricho93** [comment]
Hey, indeed this fix isn't live yet, it will be out with the next media-chrome release. I'll let you know here when it's live!

**Comment by luwes** [comment]
@geosigno the fix should be live in https://github.com/muxinc/media-chrome/releases/tag/v4.12.0

could you provide a codesandbox with a reproduction of the issue? that would help a lot with debugging. thanks!
